// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class ArticleImage
{
    public int ImageId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? LastEditTime { get; set; }

    public string Image { get; set; }

    public int SortOrder { get; set; }

    public int ArticleId { get; set; }

    public bool IsExist { get; set; }
}