// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Article
{
    public int ArticleId { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? LastEditTime { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int Status { get; set; }

    public int ViewCount { get; set; }

    public int ReportedCount { get; set; }

    public DateTime? LastReported { get; set; }

    public DateTime? EventStartDate { get; set; }

    public DateTime? EventEndDate { get; set; }

    public string EventLocation { get; set; }

    public bool IsExist { get; set; }

    public int UserId { get; set; }

    public int CategoryId { get; set; }
}