// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Chatroom
{
    public int ChatroomId { get; set; }

    public int UserId1 { get; set; }

    public int UserId2 { get; set; }

    public bool IsExist { get; set; }

    public DateTime CreateAt { get; set; }

    public bool IsActive { get; set; }

    public int? DeleteTypeId { get; set; }

    public string DeleteNote { get; set; }
}