// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class DeleteReasonType
{
    public int DeleteTypeId { get; set; }

    public string ReasonTitle { get; set; }

    public bool? IsExist { get; set; }

    public DateTime? LastEditTime { get; set; }

    public DateTime CreateAt { get; set; }
}