// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class ENewsletter
{
    public int NewsLetterId { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Content { get; set; }

    public DateTime? PublishDate { get; set; }

    public string Category { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public int UserId { get; set; }
}