// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Faq
{
    public int Faqid { get; set; }

    public string QuestionType { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public string Note { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? StoppedDate { get; set; }

    public string Status { get; set; }

    public bool IsExist { get; set; }
}