// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Following
{
    public int FollowingIdPk { get; set; }

    public int UserId { get; set; }

    public int FollowingId { get; set; }

    public bool IsExist { get; set; }

    public DateTime CreateAt { get; set; }
}