// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class GameContent
{
    public int GameId { get; set; }

    public string GameName { get; set; }

    public string Questions { get; set; }

    public string AnswersDetail { get; set; }

    public bool Answers { get; set; }

    public bool IsActive { get; set; }

    public int Rewards { get; set; }

    public string Type { get; set; }
}