// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class GameHistory
{
    public int HistoryId { get; set; }

    public int GameId { get; set; }

    public bool? StageClear { get; set; }

    public DateTime? LastPlayedDate { get; set; }

    public bool ReceivedReward { get; set; }

    public int PlayerId { get; set; }

    public virtual PlayerProfile Player { get; set; }
}