// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class LineBot
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public DateTime ChatDate { get; set; }

    public string QuestionType { get; set; }

    public string ChiefComplaint { get; set; }

    public string ChatContent { get; set; }
}