// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Message
{
    public long MessageId { get; set; }

    public string Content { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreateAt { get; set; }

    public string Image { get; set; }

    public bool IsExist { get; set; }

    public int SenderId { get; set; }

    public int ChatroomId { get; set; }
}