// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class OauthTable
{
    public int OauthId { get; set; }

    public string AuthType { get; set; }

    public string ProviderKey { get; set; }

    public string RefreshToken { get; set; }

    public string AccessToken { get; set; }

    public int UserId { get; set; }
}