// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PawsPort.Models;

public partial class PetDbContext : DbContext
{
    public PetDbContext(DbContextOptions<PetDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdoptionRecord> AdoptionRecords { get; set; }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<ArticleImage> ArticleImages { get; set; }

    public virtual DbSet<ArticleTagMap> ArticleTagMaps { get; set; }

    public virtual DbSet<Bookmark> Bookmarks { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Chatroom> Chatrooms { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<DeleteReasonType> DeleteReasonTypes { get; set; }

    public virtual DbSet<ENewsletter> ENewsletters { get; set; }

    public virtual DbSet<Faq> Faqs { get; set; }

    public virtual DbSet<Following> Followings { get; set; }

    public virtual DbSet<GameContent> GameContents { get; set; }

    public virtual DbSet<GameHistory> GameHistories { get; set; }

    public virtual DbSet<HealthPassport> HealthPassports { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<ItemAcquisitionLog> ItemAcquisitionLogs { get; set; }

    public virtual DbSet<LineBot> LineBots { get; set; }

    public virtual DbSet<LoginActivity> LoginActivities { get; set; }

    public virtual DbSet<MedicalHistory> MedicalHistories { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<MissingReport> MissingReports { get; set; }

    public virtual DbSet<Notify> Notifies { get; set; }

    public virtual DbSet<OauthTable> OauthTables { get; set; }

    public virtual DbSet<Pet> Pets { get; set; }

    public virtual DbSet<PlayerProfile> PlayerProfiles { get; set; }

    public virtual DbSet<PointTransaction> PointTransactions { get; set; }

    public virtual DbSet<QARecord> QARecords { get; set; }

    public virtual DbSet<RoleTable> RoleTables { get; set; }

    public virtual DbSet<SkinShop> SkinShops { get; set; }

    public virtual DbSet<SystemTable> SystemTables { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<UserAuthTable> UserAuthTables { get; set; }

    public virtual DbSet<UserSystemRole> UserSystemRoles { get; set; }

    public virtual DbSet<UserTable> UserTables { get; set; }

    public virtual DbSet<VaccinationStatus> VaccinationStatuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdoptionRecord>(entity =>
        {
            entity.HasKey(e => e.AdoptionId).HasName("PK__Adoption__38BABF2CAA88661F");

            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.ReturnReason).HasMaxLength(255);
        });

        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.ArticleId).HasName("PK__Article__9C6270C8C7C8D7FE");

            entity.ToTable("Article");

            entity.Property(e => e.ArticleId).HasColumnName("ArticleID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.DeleteNote).HasMaxLength(200);
            entity.Property(e => e.DeleteTypeId).HasColumnName("DeleteTypeID");
            entity.Property(e => e.EventEndDate).HasColumnType("datetime");
            entity.Property(e => e.EventLocation).HasMaxLength(1000);
            entity.Property(e => e.EventStartDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.LastReported).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<ArticleImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__ArticleI__7516F4EC588AD160");

            entity.ToTable("ArticleImage");

            entity.HasIndex(e => new { e.ArticleId, e.SortOrder }, "IX_Unique_ArticleImage_Sort")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.ImageId).HasColumnName("ImageID");
            entity.Property(e => e.ArticleId).HasColumnName("ArticleID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.SortOrder).HasDefaultValue(1);
        });

        modelBuilder.Entity<ArticleTagMap>(entity =>
        {
            entity.HasKey(e => e.ArticleTagMapId).HasName("PK__ArticleT__DFDFD7744AD2B92E");

            entity.ToTable("ArticleTagMap");

            entity.HasIndex(e => new { e.ArticleId, e.TagId }, "IX_Unique_Article_Tag_Active")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.ArticleTagMapId).HasColumnName("ArticleTagMapID");
            entity.Property(e => e.ArticleId).HasColumnName("ArticleID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.TagId).HasColumnName("TagID");
        });

        modelBuilder.Entity<Bookmark>(entity =>
        {
            entity.HasKey(e => e.BookmarkId).HasName("PK__Bookmark__541A3A913DCD7448");

            entity.ToTable("Bookmark");

            entity.HasIndex(e => new { e.UserId, e.ArticleId }, "IX_Unique_Bookmark_Active")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.BookmarkId).HasColumnName("BookmarkID");
            entity.Property(e => e.ArticleId).HasColumnName("ArticleID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Category__19093A2B48246B39");

            entity.ToTable("Category");

            entity.HasIndex(e => new { e.ParentId, e.CategoryName }, "IX_Unique_CategoryName_Per_Parent")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryDescription).HasMaxLength(1000);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
        });

        modelBuilder.Entity<Chatroom>(entity =>
        {
            entity.HasKey(e => e.ChatroomId).HasName("PK__Chatroom__B83BDF28709CEA28");

            entity.HasIndex(e => new { e.UserId1, e.UserId2 }, "IX_Unique_Chatroom_Active")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.ChatroomId).HasColumnName("ChatroomID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.DeleteNote).HasMaxLength(200);
            entity.Property(e => e.DeleteTypeId).HasColumnName("DeleteTypeID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.UserId1).HasColumnName("UserID_1");
            entity.Property(e => e.UserId2).HasColumnName("UserID_2");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__Comment__C3B4DFAAB450E997");

            entity.ToTable("Comment");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.ArticleId).HasColumnName("ArticleID");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.DeleteNote).HasMaxLength(200);
            entity.Property(e => e.DeleteTypeId).HasColumnName("DeleteTypeID");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.LastReported).HasColumnType("datetime");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<DeleteReasonType>(entity =>
        {
            entity.HasKey(e => e.DeleteTypeId).HasName("PK__DeleteRe__4ACBE211F77AB47C");

            entity.ToTable("DeleteReasonType");

            entity.Property(e => e.DeleteTypeId).HasColumnName("DeleteTypeID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.ReasonTitle)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ENewsletter>(entity =>
        {
            entity.HasKey(e => e.NewsLetterId).HasName("PK__E-Newsle__7F740FC2CCDFD833");

            entity.ToTable("E-Newsletter");

            entity.Property(e => e.Category).HasMaxLength(20);
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Note).HasMaxLength(100);
            entity.Property(e => e.PublishDate).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(100);
            entity.Property(e => e.Summary)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Faq>(entity =>
        {
            entity.HasKey(e => e.Faqid).HasName("PK__FAQ__4B89D1823B3A23F9");

            entity.ToTable("FAQ");

            entity.Property(e => e.Faqid).HasColumnName("FAQId");
            entity.Property(e => e.Answer)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.Note).HasMaxLength(100);
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.QuestionType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.StoppedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Following>(entity =>
        {
            entity.HasKey(e => e.FollowingIdPk).HasName("PK__Followin__A05EF6902DED6E44");

            entity.ToTable("Following");

            entity.HasIndex(e => new { e.UserId, e.FollowingId }, "IX_Unique_Following_Active")
                .IsUnique()
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.FollowingIdPk).HasColumnName("FollowingID_PK");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.FollowingId).HasColumnName("FollowingID");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<GameContent>(entity =>
        {
            entity.HasKey(e => e.GameId).HasName("PK__GameCont__2AB897FD41956010");

            entity.ToTable("GameContent");

            entity.Property(e => e.AnswersDetail)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.GameName)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Questions)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Type).HasMaxLength(50);
        });

        modelBuilder.Entity<GameHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__GameHist__4D7B4ABDBB9877D8");

            entity.ToTable("GameHistory");

            entity.Property(e => e.LastPlayedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Player).WithMany(p => p.GameHistories)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GameHisto__Playe__681373AD");
        });

        modelBuilder.Entity<HealthPassport>(entity =>
        {
            entity.HasKey(e => e.PassportId).HasName("PK__HealthPa__185653D0BB54D04B");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Photo).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.InventoryId).HasName("PK__Inventor__F5FDE6B343796064");

            entity.ToTable("Inventory");

            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.HasOne(d => d.Player).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__Playe__6EC0713C");

            entity.HasOne(d => d.Skin).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.SkinId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__SkinI__6FB49575");
        });

        modelBuilder.Entity<ItemAcquisitionLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__ItemAcqu__5E54864846CD7839");

            entity.ToTable("ItemAcquisitionLog");

            entity.Property(e => e.AcquireType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateTime).HasColumnType("datetime");

            entity.HasOne(d => d.Player).WithMany(p => p.ItemAcquisitionLogs)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemAcqui__Playe__72910220");

            entity.HasOne(d => d.Skin).WithMany(p => p.ItemAcquisitionLogs)
                .HasForeignKey(d => d.SkinId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ItemAcqui__SkinI__73852659");
        });

        modelBuilder.Entity<LineBot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LINE Bot__3214EC0764BF7098");

            entity.ToTable("LINE Bot");

            entity.Property(e => e.ChatContent)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.ChatDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ChiefComplaint)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.QuestionType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ReplyContent).HasMaxLength(500);
            entity.Property(e => e.ReplyDate).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(20);
        });

        modelBuilder.Entity<LoginActivity>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__LoginAct__5E5499A811127502");

            entity.ToTable("LoginActivity");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.AuthType).HasMaxLength(20);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(50)
                .HasColumnName("IPAddress");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.LoginTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
        });

        modelBuilder.Entity<MedicalHistory>(entity =>
        {
            entity.HasKey(e => e.MedicalDetailId).HasName("PK__MedicalH__DC48BDDE8FD6DAA8");

            entity.ToTable("MedicalHistory");

            entity.Property(e => e.MedicalDetailId).HasColumnName("MedicalDetailID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Disease).HasMaxLength(100);
            entity.Property(e => e.DiseaseTreatment).HasMaxLength(255);
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.Time).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__C87C037CE8840703");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.ChatroomId).HasColumnName("ChatroomID");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.DeleteNote).HasMaxLength(200);
            entity.Property(e => e.DeleteTypeId).HasColumnName("DeleteTypeID");
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
        });

        modelBuilder.Entity<MissingReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__MissingR__D5BD48059F8ABD5D");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.LastSeenDate).HasColumnType("datetime");
            entity.Property(e => e.LastSeenLat).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.LastSeenLng).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.LostCity).HasMaxLength(20);
            entity.Property(e => e.LostDistrict).HasMaxLength(20);
            entity.Property(e => e.LostLocation).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Photo).HasMaxLength(100);
            entity.Property(e => e.Size).HasMaxLength(20);
            entity.Property(e => e.Species).HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Notify>(entity =>
        {
            entity.HasKey(e => e.NotifyId).HasName("PK__Notify__AD54A2DC29EB0812");

            entity.ToTable("Notify");

            entity.HasIndex(e => new { e.UserId, e.IsRead, e.CreateAt }, "IX_Notification_User_Read")
                .IsDescending(false, false, true)
                .HasFilter("([IsExist]=(1))");

            entity.Property(e => e.NotifyId).HasColumnName("NotifyID");
            entity.Property(e => e.Content).HasMaxLength(500);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<OauthTable>(entity =>
        {
            entity.HasKey(e => e.OauthId).HasName("PK__OAuthTab__BE2FE48D43678C95");

            entity.ToTable("OAuthTable");

            entity.Property(e => e.AccessToken).HasMaxLength(255);
            entity.Property(e => e.AuthType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ProviderKey)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
        });

        modelBuilder.Entity<Pet>(entity =>
        {
            entity.HasKey(e => e.PetId).HasName("PK__Pets__48E53862966856FB");

            entity.Property(e => e.BehavioralTraits).HasMaxLength(255);
            entity.Property(e => e.CoatColor).HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Microchip)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Photo).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<PlayerProfile>(entity =>
        {
            entity.HasKey(e => e.PlayerId).HasName("PK__PlayerPr__4A4E74C87D9A36FA");

            entity.ToTable("PlayerProfile");

            entity.HasIndex(e => e.UserId, "UQ__PlayerPr__1788CC4DD1DD9E79").IsUnique();

            entity.Property(e => e.UserName).HasMaxLength(10);
        });

        modelBuilder.Entity<PointTransaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__PointTra__55433A6BF2B38774");

            entity.ToTable("PointTransaction");

            entity.Property(e => e.TransactionDate).HasColumnType("datetime");
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Player).WithMany(p => p.PointTransactions)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PointTran__Playe__6BE40491");

            entity.HasOne(d => d.Skin).WithMany(p => p.PointTransactions)
                .HasForeignKey(d => d.SkinId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PointTran__SkinI__6AEFE058");
        });

        modelBuilder.Entity<QARecord>(entity =>
        {
            entity.HasKey(e => e.Qaid).HasName("PK__Q&A Reco__DFA593A04EEC2738");

            entity.ToTable("Q&A Record");

            entity.Property(e => e.Qaid).HasColumnName("QAId");
            entity.Property(e => e.ChatContent)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.ChiefComplaint)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Csname)
                .HasMaxLength(20)
                .HasColumnName("CSName");
            entity.Property(e => e.Note).HasMaxLength(100);
            entity.Property(e => e.QuestionDate)
                .HasDefaultValueSql("(getdate())", "DF__Q&A Recor__Quest__41EDCAC5")
                .HasColumnType("datetime");
            entity.Property(e => e.QuestionType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ReplyContent).HasMaxLength(100);
            entity.Property(e => e.ReplyDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<RoleTable>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__RoleTabl__8AFACE1A4302FEFF");

            entity.ToTable("RoleTable");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<SkinShop>(entity =>
        {
            entity.HasKey(e => e.SkinId).HasName("PK__SkinShop__9A70C30B211161AE");

            entity.ToTable("SkinShop");

            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.IsAvailable).HasDefaultValue(true);
            entity.Property(e => e.IsDel).HasColumnName("IsDEL");
            entity.Property(e => e.SkinImage)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SkinName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<SystemTable>(entity =>
        {
            entity.HasKey(e => e.SystemId).HasName("PK__SystemTa__9394F68A9EE4DCCC");

            entity.ToTable("SystemTable");

            entity.Property(e => e.Description).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.SystemName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__Tags__657CFA4C2FB74DE2");

            entity.HasIndex(e => e.TagName, "UQ__Tags__BDE0FD1DB6B980DD").IsUnique();

            entity.Property(e => e.TagId).HasColumnName("TagID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("Create_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsExist).HasDefaultValue(true);
            entity.Property(e => e.LastEditTime).HasColumnType("datetime");
            entity.Property(e => e.ParentCategoryId).HasColumnName("ParentCategoryID");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<UserAuthTable>(entity =>
        {
            entity.HasKey(e => e.AuthId).HasName("PK__UserAuth__12C15DD35740C612");

            entity.ToTable("UserAuthTable");

            entity.HasIndex(e => e.UserId, "UQ__UserAuth__1788CC4D17BF083C").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__UserAuth__A9D10534C5322068").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EmailConfirmationToken).HasMaxLength(255);
            entity.Property(e => e.EmailTokenExpiry).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PasswordResetExpires).HasColumnType("datetime");
            entity.Property(e => e.PasswordResetToken).HasMaxLength(255);
        });

        modelBuilder.Entity<UserSystemRole>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("PK__UserSyst__8B5781BDA7DD0827");

            entity.ToTable("UserSystemRole");

            entity.Property(e => e.MappingId).HasColumnName("MappingID");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<UserTable>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserTabl__1788CC4C48AC0435");

            entity.ToTable("UserTable");

            entity.Property(e => e.City).HasMaxLength(10);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteDay).HasColumnType("datetime");
            entity.Property(e => e.HasPriorExp).HasDefaultValue(false);
            entity.Property(e => e.IsSubscribe).HasDefaultValue(true);
            entity.Property(e => e.IsVerify).HasDefaultValue(false);
            entity.Property(e => e.Job).HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.Phone).HasMaxLength(10);
            entity.Property(e => e.Point).HasDefaultValue(0);
            entity.Property(e => e.Status).HasDefaultValue(true);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<VaccinationStatus>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__Vaccinat__4D7B4ABD40F27105");

            entity.ToTable("VaccinationStatus");

            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.Time).HasColumnType("datetime");
            entity.Property(e => e.Type).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}