// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class PlayerProfile
{
    public int PlayerId { get; set; }

    public int UserId { get; set; }

    public int? CurrentPoint { get; set; }

    public string UserName { get; set; }

    public virtual ICollection<GameHistory> GameHistories { get; set; } = new List<GameHistory>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<ItemAcquisitionLog> ItemAcquisitionLogs { get; set; } = new List<ItemAcquisitionLog>();

    public virtual ICollection<PointTransaction> PointTransactions { get; set; } = new List<PointTransaction>();
}