// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class PointRecord
{
    public int PointDetailId { get; set; }

    public int? Point { get; set; }

    public string Upstream { get; set; }

    public DateTime? CreateTime { get; set; }

    public int PlayerId { get; set; }

    public int? GameId { get; set; }
}