// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class PointTransaction
{
    public int TransactionId { get; set; }

    public int? Amount { get; set; }

    public string TransactionType { get; set; }

    public int GameId { get; set; }

    public int SkinId { get; set; }

    public int? PassportId { get; set; }

    public int PlayerId { get; set; }

    public DateTime TransactionDate { get; set; }
}