// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class QARecord
{
    public int Qaid { get; set; }

    public int UserId { get; set; }

    public DateTime QuestionDate { get; set; }

    public string QuestionType { get; set; }

    public string ChiefComplaint { get; set; }

    public string ChatContent { get; set; }

    public string Csname { get; set; }

    public string ReplyContent { get; set; }

    public string Note { get; set; }

    public DateTime ReplyDate { get; set; }

    public int? Score { get; set; }
}