// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class SkinShop
{
    public int SkinId { get; set; }

    public string SkinName { get; set; }

    public string Description { get; set; }

    public int Price { get; set; }

    public string SkinImage { get; set; }

    public bool IsAvailable { get; set; }

    public bool? IsDel { get; set; }
}