// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class SystemTable
{
    public int SystemId { get; set; }

    public string SystemName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }
}