// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public int? ParentCategoryId { get; set; }

    public bool? IsExist { get; set; }

    public DateTime? LastEditTime { get; set; }

    public DateTime CreateAt { get; set; }

    public bool IsActive { get; set; }
}