// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawsPort.Models;

public partial class UserAuthTable
{
    public int AuthId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime? PasswordResetExpires { get; set; }

    public string PasswordResetToken { get; set; }

    public int UserId { get; set; }
}